# Rustfmt configuration file - only stable options

# Maximum width of each line
max_width = 100

# Number of spaces per tab
tab_spaces = 4

# Use spaces instead of tabs
hard_tabs = false

# Maximum width of function call arguments before falling back to vertical formatting
fn_call_width = 60

# Maximum width in a struct literal before falling back to vertical formatting
struct_lit_width = 18

# Maximum width of an array literal before falling back to vertical formatting
array_width = 60

# Maximum width of a chain to fit on a single line
chain_width = 60

# Maximum width of a single line if-else expression
single_line_if_else_max_width = 50

# Put a trailing comma after a block based match arm
match_block_trailing_comma = false

# Use field init shorthand if possible
use_field_init_shorthand = true

# Use try shorthand
use_try_shorthand = true

# Edition to use
edition = "2024"

# Reorder import statements alphabetically
reorder_imports = true

# Newline style
newline_style = "Unix"
