[graph]
targets = []

[licenses]
confidence-threshold = 0.8
allow = [
    # GPL family - copyleft licenses
    "GPL-3.0",
    "GPL-3.0-only",
    "GPL-3.0-or-later",
    "GPL-2.0",
    "GPL-2.0-only",
    "GPL-2.0-or-later",
    "LGPL-3.0",
    "LGPL-3.0-only",
    "LGPL-3.0-or-later",
    "LGPL-2.1",
    "LGPL-2.1-only",
    "LGPL-2.1-or-later",
    "AGPL-3.0",
    "AGPL-3.0-only",
    "AGPL-3.0-or-later",

    # Permissive licenses compatible with GPL v3
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "MPL-2.0",

    # Public domain and similar
    "CC0-1.0",
    "Unlicense",
    "0BSD",

    # Other compatible licenses
    "Unicode-DFS-2016",
    "Zlib",
]

deny = [
    "CC-BY-NC-4.0",
    "CC-BY-ND-4.0",
    "CC-BY-NC-ND-4.0",
    "GPL-1.0",
    "EUPL-1.1",
    "OSL-3.0",
    "BSD-4-Clause",
    "BSD-4-Clause-UC",
    "JSON",
]

[bans]
multiple-versions = "warn"
wildcards = "allow"

[advisories]
db-path = "~/.cargo/advisory-dbs"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "warn"
unmaintained = "workspace"

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
